######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 21 14:29:43 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Toolbar.hpp
SOURCES += main.cpp
