# circle ci config (github)
version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - checkout

#      - run:
#          name: Greeting
#          command: echo Hello, world.

      - run: date

## 00: language-basics
      - run: cd 00__cpp__language-basics/abstract_class && make && ./abstractclass.exe
      - run: cd 00__cpp__language-basics/ambiguous_names && make && ./ambiguousnames.exe
      - run: cd 00__cpp__language-basics/arrays-and-assert && make && ./arrayandassert.exe || echo "Ok"
      - run: cd 00__cpp__language-basics/callback_version && make && ./callbackversion.exe
      - run: cd 00__cpp__language-basics/callback_plain && make && ./callbackplain.exe
      - run: cd 00__cpp__language-basics/class && g++ -m32 -S -fno-dwarf2-cfi-asm ./simpleclass.cpp && nl simpleclass.s
      - run: cd 00__cpp__language-basics/const_basics && make && ./constbasics.exe
      - run: cd 00__cpp__language-basics/const_cast && make && ./constcast.exe
      - run: cd 00__cpp__language-basics/copy_constructor && make && ./copyconstructor.exe
      - run: cd 00__cpp__language-basics/exception1 && make && ./exception1.exe
      - run: cd 00__cpp__language-basics/exception2 && make && ./exception2.exe
      - run: cd 00__cpp__language-basics/exception3 && make && ./exception3.exe
      - run: cd 00__cpp__language-basics/exception4 && make && ./exception4.exe
      - run: cd 00__cpp__language-basics/explicit_constructor && make && ./explicitconstructor.exe
      - run: cd 00__cpp__language-basics/new-delete1 && make && ./newdelete1.exe
      - run: cd 00__cpp__language-basics/new-delete2 && make && ./newdelete2.exe
      - run: cd 00__cpp__language-basics/no_reference_on_locals && make && ./noreferenceonlocals.exe
      - run: cd 00__cpp__language-basics/operator__and && cat ./operatorand.cpp
      - run: cd 00__cpp__language-basics/operator__assignment && make && ./operatorassignment.exe
      - run: cd 00__cpp__language-basics/operator__comma && cat ./operatorcomma.cpp
      - run: cd 00__cpp__language-basics/operator__equals && make && ./operatorequals.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete && make && ./operatornewanddelete.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete-freelist && make && ./operatornewanddeletefreelist.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete-memorypool && make && ./operatornewanddeletememorypool.exe
      - run: cd 00__cpp__language-basics/operator__new-handler && make && ./operatornewhandler.exe
      - run: cd 00__cpp__language-basics/operator__or && cat operatoror.cpp
      - run: cd 00__cpp__language-basics/operator__parentheses && cat operatorparentheses.txt
      - run: cd 00__cpp__language-basics/operator__streams && make && ./operatorstreams.exe
      - run: cd 00__cpp__language-basics/operator__subscript && make && ./operatorsubscript.exe
      - run: cd 00__cpp__language-basics/pass_by_what && make && ./passbywhat.exe
      - run: cd 00__cpp__language-basics/passing_function_parameter && make && ./passingfunctionparameter.exe
      - run: cd 00__cpp__language-basics/pointer1 && make && ./pointer1.exe
      - run: cd 00__cpp__language-basics/pointer2 && make && ./pointer2.exe
      - run: cd 00__cpp__language-basics/pointer3 && make && ./pointer3.exe
      - run: cd 00__cpp__language-basics/pointer4 && make && ./pointer4.exe
      - run: cd 00__cpp__language-basics/pointer5 && make && ./pointer5.exe
      - run: cd 00__cpp__language-basics/pointer6 && make && ./pointer6.exe || echo "OK"
      - run: cd 00__cpp__language-basics/pointer7 && make && ./pointer7.exe
      - run: cd 00__cpp__language-basics/rule_of_big_three && make && ./ruleofbigthree.exe
      - run: cd 00__cpp__language-basics/slicing_problem && make && ./slicingproblem.exe
      - run: cd 00__cpp__language-basics/template__class && make && ./templateclass.exe
      - run: cd 00__cpp__language-basics/template__function && make && ./templatefunction.exe
      - run: cd 00__cpp__language-basics/template__simple && make && ./templatesimple.exe
      - run: cd 00__cpp__language-basics/template__template-in-template-class && make && ./templatetemplateintemplateclass.exe
      - run: cd 00__cpp__language-basics/typeinfo__typeid && make && ./typeinfotypeid.exe
      - run: cd 00__cpp__language-basics/typeinfo__typeinfo-wrapper-cpp0x && make && ./typeinfotypeinfowrapper.exe
      - run: cd 00__cpp__language-basics/typeinfo__typeof-cpp0x && make && ./typeinfotypeof.exe
      - run: cd 00__cpp__language-basics/userinput && make && ./userinput.exe
      - run: cd 00__cpp__language-basics/virtual && make && ./virtual.exe
      - run: cd 00__cpp__language-basics/virtual__missing-virtual && make && ./virtualmissingvirtual.exe
      - run: cd 00__cpp__language-basics/virtual__nonvirtual-inheritance && make && ./virtualnonvirtualinheritance.exe
      - run: cd 00__cpp__language-basics/virtual__virtual-destructor && make && ./virtualvirtualdestructor.exe
      - run: cd 00__cpp__language-basics/virtual__virtual-inheritance && make && ./virtualvirtualinheritance.exe

## 10: language-techniques
      - run: cd 10__cpp__language-techniques/allocator_for_small_objects && make && ./allocatorforsmallobjects.exe
      - run: cd 10__cpp__language-techniques/binder_functorbinder && make && ./binderfunctorbinder.exe
      - run: cd 10__cpp__language-techniques/binder_thisbinder && make && ./binderthisbinder.exe
      - run: cd 10__cpp__language-techniques/compiletimechecks && make || echo "OK"
      - run: cd 10__cpp__language-techniques/compiletimechecks__assert-type-check && make && ./compiletimechecksasserttypecheck.exe || echo "OK"
      - run: cd 10__cpp__language-techniques/compiletimechecks__error-messages || echo "OK"
      - run: cd 10__cpp__language-techniques/compiletimechecks__improved && make && ./compiletimechecksimproved.exe
      - run: cd 10__cpp__language-techniques/destructor-and-delete && make && ./destructoranddelete.exe
      - run: cd 10__cpp__language-techniques/double_dispatching && make && ./doubledispatching.exe
      - run: cd 10__cpp__language-techniques/dummytypes__empty-type && make && ./dummytypesemptytype.exe
      

