# circle ci config (github)
version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - checkout

#      - run:
#          name: Greeting
#          command: echo Hello, world.

      - run: date

## 00: language-basics
      - run: cd 00__cpp__language-basics/abstract_class && make && ./*.exe
      - run: cd 00__cpp__language-basics/ambiguous_names && make && ./*.exe
      - run: cd 00__cpp__language-basics/arrays-and-assert && make && ./*.exe || echo "Ok"
      - run: cd 00__cpp__language-basics/callback_version && make && ./*.exe
      - run: cd 00__cpp__language-basics/callback_plain && make && ./*.exe
      - run: cd 00__cpp__language-basics/class && g++ -m32 -S -fno-dwarf2-cfi-asm ./simpleclass.cpp && nl simpleclass.s
      - run: cd 00__cpp__language-basics/const_basics && make && ./*.exe
      - run: cd 00__cpp__language-basics/const_cast && make && ./*.exe
      - run: cd 00__cpp__language-basics/copy_constructor && make && ./*.exe
      - run: cd 00__cpp__language-basics/exception1 && make && ./*.exe
      - run: cd 00__cpp__language-basics/exception2 && make && ./*.exe
      - run: cd 00__cpp__language-basics/exception3 && make && ./*.exe
      - run: cd 00__cpp__language-basics/exception4 && make && ./*.exe
      - run: cd 00__cpp__language-basics/explicit_constructor && make && ./*.exe
      - run: cd 00__cpp__language-basics/new-delete1 && make && ./*.exe
      - run: cd 00__cpp__language-basics/new-delete2 && make && ./*.exe
      - run: cd 00__cpp__language-basics/no_reference_on_locals && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__and && cat ./operatorand.cpp
      - run: cd 00__cpp__language-basics/operator__assignment && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__comma && cat ./operatorcomma.cpp
      - run: cd 00__cpp__language-basics/operator__equals && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete-freelist && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete-memorypool && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__new-handler && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__or && cat operatoror.cpp
      - run: cd 00__cpp__language-basics/operator__parentheses && cat operatorparentheses.txt
      - run: cd 00__cpp__language-basics/operator__streams && make && ./*.exe
      - run: cd 00__cpp__language-basics/operator__subscript && make && ./*.exe
      - run: cd 00__cpp__language-basics/pass_by_what && make && ./*.exe
      - run: cd 00__cpp__language-basics/passing_function_parameter && make && ./*.exe
      - run: cd 00__cpp__language-basics/pointer1 && make && ./*.exe
      - run: cd 00__cpp__language-basics/pointer2 && make && ./*.exe
      - run: cd 00__cpp__language-basics/pointer3 && make && ./*.exe
      - run: cd 00__cpp__language-basics/pointer4 && make && ./*.exe
      - run: cd 00__cpp__language-basics/pointer5 && make && ./*.exe
      - run: cd 00__cpp__language-basics/pointer6 && make && ./*.exe || echo "OK"
      - run: cd 00__cpp__language-basics/pointer7 && make && ./*.exe
      - run: cd 00__cpp__language-basics/rule_of_big_three && make && ./*.exe
      - run: cd 00__cpp__language-basics/slicing_problem && make && ./*.exe
      - run: cd 00__cpp__language-basics/template__class && make && ./*.exe
      - run: cd 00__cpp__language-basics/template__function && make && ./*.exe
      - run: cd 00__cpp__language-basics/template__simple && make && ./*.exe
      - run: cd 00__cpp__language-basics/template__template-in-template-class && make && ./*.exe
      - run: cd 00__cpp__language-basics/typeinfo__typeid && make && ./*.exe
      - run: cd 00__cpp__language-basics/typeinfo__typeinfo-wrapper-cpp0x && make && ./*.exe
      - run: cd 00__cpp__language-basics/typeinfo__typeof-cpp0x && make && ./*.exe
      - run: cd 00__cpp__language-basics/userinput && make && ./*.exe
      - run: cd 00__cpp__language-basics/virtual && make && ./*.exe
      - run: cd 00__cpp__language-basics/virtual__missing-virtual && make && ./*.exe
      - run: cd 00__cpp__language-basics/virtual__nonvirtual-inheritance && make && ./*.exe
      - run: cd 00__cpp__language-basics/virtual__virtual-destructor && make && ./*.exe
      - run: cd 00__cpp__language-basics/virtual__virtual-inheritance && make && ./*.exe

## 10: language-techniques
      - run: cd 10__cpp__language-techniques/allocator_for_small_objects && make && ./*.exe
      - run: cd 10__cpp__language-techniques/binder_functorbinder && make && ./*.exe
      - run: cd 10__cpp__language-techniques/binder_thisbinder && make && ./*.exe
      - run: cd 10__cpp__language-techniques/compiletimechecks && make || echo "OK"
      - run: cd 10__cpp__language-techniques/compiletimechecks__assert-type-check && make && ./*.exe || echo "OK"
      - run: cd 10__cpp__language-techniques/compiletimechecks__error-messages || echo "OK"
      - run: cd 10__cpp__language-techniques/compiletimechecks__improved && make && ./*.exe
      - run: cd 10__cpp__language-techniques/destructor-and-delete && make && ./*.exe
      - run: cd 10__cpp__language-techniques/double_dispatching && make && ./*.exe
      - run: cd 10__cpp__language-techniques/dummytypes__empty-type && make && ./*.exe
      - run: cd 10__cpp__language-techniques/dummytypes__null-type && make && ./*.exe
      - run: cd 10__cpp__language-techniques/function_pointer && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-binder-fails-cpp0x && make && ./*.exe || echo "OK"
#      - run: cd 10__cpp__language-techniques/functor__functor-binder-fails-cpp11 && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-bridge && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-bridge-facade && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-handler-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-handler-cpp11 && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-loki-style-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-tests-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__functor-with-returntype-conversion-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__member-functions-functionpointer && make && ./*.exe
      - run: cd 10__cpp__language-techniques/functor__member-functions-functor-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/inline && make && ./*.exe
      - run: cd 10__cpp__language-techniques/lazy_fetching && make && ./*.exe
      - run: cd 10__cpp__language-techniques/local_class && make && ./*.exe
      - run: cd 10__cpp__language-techniques/mixin_class && make && ./*.exe
      - run: cd 10__cpp__language-techniques/policy__optional-functionality-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/policy__policy-classes-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/policy__policy-design-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/policy__structure-policy-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/protocol_class-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/protocol_class-cpp11 && make && ./*.exe
      - run: cd 10__cpp__language-techniques/cts__class-template-specialization && make && ./*.exe
      - run: cd 10__cpp__language-techniques/cts__default-params && make && ./*.exe
      - run: cd 10__cpp__language-techniques/cts__interface && make && ./*.exe
      - run: cd 10__cpp__language-techniques/cts__pointers && make && ./*.exe
      - run: cd 10__cpp__language-techniques/cts__polymorphism && make && ./*.exe
      - run: cd 10__cpp__language-techniques/refcount__baseclass-design && make && ./*.exe
      - run: cd 10__cpp__language-techniques/refcount__basics && make && ./*.exe
      - run: cd 10__cpp__language-techniques/refcount__copy-on-write && make && ./*.exe
      - run: cd 10__cpp__language-techniques/refcount__copy-on-write-shareable && make && ./*.exe
      - run: cd 10__cpp__language-techniques/refcount__costumized-and-comma-example && make && ./*.exe
      - run: cd 10__cpp__language-techniques/stack__heap-never-classes && make && ./*.exe
      - run: cd 10__cpp__language-techniques/stack__heap-only-classes && make && ./*.exe
      - run: cd 10__cpp__language-techniques/traits__fundamental-type-traits-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/traits__optimized-parameter-traits-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/traits__pointer-to-member-traits-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/traits__pointer-traits-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/traits__stripping-qualifiers-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/typelist__new-style-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/typelist__no-duplicates-cpp0x && make && ./*.exe
      - run: cd 10__cpp__language-techniques/typelist__old-style-cpp0x && make && ./*.exe
#      - run: cd 10__cpp__language-techniques/typelist__tylelist-linear-cpp0x__TODO && make && ./*.exe
#      - run: cd 10__cpp__language-techniques/typelist__tylelist-scattered-cpp0x__TODO && make && ./*.exe
      - run: cd 10__cpp__language-techniques/typelist__cpp11 && make && ./*.exe
      - run: cd 10__cpp__language-techniques/typemapping__primitive_to_any_type && make && ./*.exe
      - run: cd 10__cpp__language-techniques/typemapping__type_to_type && make && ./*.exe
     
## 20: stl
      - run: cd 20__cpp__stl/algorithm-heap_example1 && make && ./*.exe 
