# circle ci config (github)
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Installing gcc and g++
          command: 'apt-get update && apt-get install -y gcc g++'

      - run: cd cpp/00__cpp__language-basics/abstract_class && make && ./abstractclass.exe
