# circle ci config (github)
version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - checkout

#      - run:
#          name: Greeting
#          command: echo Hello, world.

      - run: date

      - run: cd 00__cpp__language-basics/abstract_class && make && ./abstractclass.exe
      - run: cd 00__cpp__language-basics/ambiguous_names && make && ./ambiguousnames.exe
      - run: cd 00__cpp__language-basics/arrays-and-assert && make && ./arrayandassert.exe || echo "Ok"
      - run: cd 00__cpp__language-basics/callback_version && make && ./callbackversion.exe
      - run: cd 00__cpp__language-basics/callback_plain && make && ./callbackplain.exe
      - run: cd 00__cpp__language-basics/class && g++ -m32 -S -fno-dwarf2-cfi-asm ./simpleclass.cpp && nl simpleclass.s
      - run: cd 00__cpp__language-basics/const_basics && make && ./constbasics.exe
      - run: cd 00__cpp__language-basics/const_cast && make && ./constcast.exe
      - run: cd 00__cpp__language-basics/copy_constructor && make && ./copyconstructor.exe
      - run: cd 00__cpp__language-basics/exception1 && make && ./exception1.exe
      - run: cd 00__cpp__language-basics/exception2 && make && ./exception2.exe
      - run: cd 00__cpp__language-basics/exception3 && make && ./exception3.exe
      - run: cd 00__cpp__language-basics/exception4 && make && ./exception4.exe
      - run: cd 00__cpp__language-basics/explicit_constructor && make && ./explicitconstructor.exe
      - run: cd 00__cpp__language-basics/new-delete1 && make && ./newdelete1.exe
      - run: cd 00__cpp__language-basics/new-delete2 && make && ./newdelete2.exe
      - run: cd 00__cpp__language-basics/no_reference_on_locals && make && ./noreferenceonlocals.exe 
      - run: cd 00__cpp__language-basics/operator__and && cat ./operatorand.cpp
      - run: cd 00__cpp__language-basics/operator__assignment && make && ./operatorassignment.exe
      - run: cd 00__cpp__language-basics/operator__comma && cat ./operatorcomma.cpp
      - run: cd 00__cpp__language-basics/operator__equals && make && ./operatorequals.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete && make && ./operatornewanddelete.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete-freelist && make && ./operatornewanddeletefreelist.exe
      - run: cd 00__cpp__language-basics/operator__new-and-delete-memorypool && make && ./operatornewanddeletememorypool.exe

