# circle ci config (github)
version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - checkout

#      - run:
#          name: Greeting
#          command: echo Hello, world.

      - run: date

      - run: cd 00__cpp__language-basics/abstract_class && make && ./abstractclass.exe
      - run: cd 00__cpp__language-basics/ambiguous_names && make && ./ambiguousnames.exe
      - run: cd 00__cpp__language-basics/arrays-and-assert && make && ./arrayandassert.exe || echo "Ok"
      - run: cd 00__cpp__language-basics/callback_version && make && ./callbackversion.exe
      - run: cd 00__cpp__language-basics/callback_plain && make && ./callbackplain.exe
      - run: cd 00__cpp__language-basics/class && g++ -m32 -S -fno-dwarf2-cfi-asm ./simpleclass.cpp && nl simpleclass.s
      - run: cd 00__cpp__language-basics/const_basic && make && ./constbasics.exe
      - run: cd 00__cpp__language-basics/const_cast && make && ./constcast.exe
      - run: cd 00__cpp__language-basics/copy_constructor && make && ./copyconstructor.exe


