######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 20 16:55:16 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Editor.cpp
