######################################################################
# Automatically generated by qmake (2.01a) qui Mai 16 04:02:39 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += image.cpp
