######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 25 01:30:40 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Plotter.h PlotterFrame.h
SOURCES += main.cpp Plotter.cpp PlotterFrame.cpp
