######################################################################
# Automatically generated by qmake (2.01a) qui Mai 16 03:57:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += image.cpp
